language: android
android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    # - platform-tools
    # - tools

    # The BuildTools version used by your project
    - tools
    - platform-tools
    - build-tools-25.0.2

    # The SDK version used to compile your project
    - android-25

  script: ./gradlew build

    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
    - sys-img-armeabi-v7a-android-22
    - sys-img-armeabi-v7a-android-25
    - sys-img-armeabi-v7a-android-24
    - sys-img-armeabi-v7a-android-23
